name: Main CI
on:
  push:
    branches:
      - main

jobs:
  scalafmt:
    name: Scalafmt lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: "temurin:17"
      - name: Scalafix checks
        run: sbt -v lint

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: "temurin:17"
      - name: Scalatest
        run: sbt -v ciTest
          



