name: Scala Steward

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:


permissions:
  contents: write
  pull-requests: write

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Scala Steward
    steps:
      - name: Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          author-name: scala-steward
          author-email: scala-steward
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
          repo-config: .scala-steward.conf
          ignore-opts-files: false